### ISSUE TITLE
Typo in the word through

### ISSUE THREAD

**Issue by doichev-kostia** [kettanaito/kettanaito.com#82]
In the [article](https://github.com/kettanaito/kettanaito.com/blob/main/content/blog/one-thing-nobody-explained-to-you-about-typescript/index.mdx#L15) about typescript

in the following sentence:
```
I dare consider myself proficient with the language, having gone thourgh my share of type gymnastics, conditional types, nested generics
```

You misspelt  ~~thourgh~~ through

Nice article by the way!

**Comment by kettanaito** [comment]
Hi, @doichev-kostia. Thanks for letting me know! Will fix that.

**Comment by kettanaito** [comment]
The fixed version is now live https://kettanaito.com/blog/one-thing-nobody-explained-to-you-about-typescript.
