### ISSUE TITLE
How is your icon designed?

### ISSUE THREAD

**Issue by aquarius-wing** [kettanaito/kettanaito.com#99]
Hello! I'm really impressed by your icon (https://kettanaito.com/logo/msw.svg).

Did you design it on your own, or did you have assistance?

I'm interested in having a similar icon designed for myself.

**Comment by kettanaito** [comment]
Hi, @aquarius-wing 👋 

I design all my icons in [Sketch](https://www.sketch.com/), but you can use any vector editor out there. I am also rather bad at it and extremely lazy, so I try to compensate that by finding creative ways to play with simple geometric shapes. For MSW logo, I split a square in half, getting two arrows. I then dragged the corners of each arrow to be slightly tilted, and brought one arrow under the other, giving it a darker shade to have a proper value contrast. Finally, I put some bold border on both to give them a proper weight on the canvas. That's about it. 

Another thing I try to do is to make the icon associate with what it's representing. MSW, for example, is a request interception library. The two arrows represent outgoing and incoming requests. Make sure your icons have a larger meaning. That always helps. 

As a fair warning, please note that the MSW icon is a part of its branding, and I'd rather you not mimic it in any way. I've had unfortunate situations where people ripped off parts of my designs, and that is not a nice thing to do. Be respectful, and have a creative icon crafting session!
